# Generated by Django 4.1.5 on 2023-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0003_blogs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='name',
        ),
    ]
